version: 2.1
orbs:
  sonar_analysis: taptapnetworks/sonar_analysis@2.1.5
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: cimg/go:1.16-node
    steps:
      - checkout
      - sonar_analysis/check_sonar_init_command
      - sonar_analysis/check_sonar_quality_gate
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
  node-tests:
    jobs:
      - node/test:
          filters:
            branches:
              only:
                - master





