version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    filters:
      branches:
        only: master
  workflows:
    node-tests:
      jobs:
        - node/test
  deploy_prod:
    requires:
      - build
      - node-tests
    filters:
      branches:
        only: master



