version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - run:
          name: check directory
          command: pwd & ls project
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
  node-tests:
    jobs:
      - node/test:
          filters:
            branches:
              only:
                - master




