version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  node: circleci/node@3.0.0
jobs:
  build:
    parameters:
      sonar.projectKey:
        type: string
        default: issamL_node-circleci
      sonar.organization:
        type: string
        default: 07issam-key
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
  node-tests:
    jobs:
      - node/test:
          filters:
            branches:
              only:
                - master





