version: 2.1
jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
orbs:
  node: circleci/node@3.0.0
  sonarcloud: extendaretail/sonarcloud@1.0.2
workflows:
  node-tests:
    jobs:
      - build:
          - context: sonarcloud
      - node/test:
          filters:
            branches:
              only:
                - master





